[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config